### ISSUE TITLE
Update the project with latest package versions

### ISSUE THREAD

**Issue by idc77** [evoxmusic/twitter-clone-rust#10]
This is sadly one of the top search results for Rust Restful on Google right now.
And it's severely outdated.

The tutorial as well is not a very good tutorial.
The focus of that tutorial is not to teach Rust and actix or diesel,
but to promote your paid service.

With this cargo.toml

```toml
[dependencies]
actix-rt = "2.9.0"
actix-web = "4.5.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
env_logger = "0.11.3"
diesel = { version = "2.1.5", features = ["postgres", "r2d2", "chrono", "uuid"] }
r2d2 = "0.8.10"
r2d2-diesel = "1.0.0"
```

this repository doesn't work anymore.
The issues are too numerous to mention all.

From a Rust RESTful tutorial I'd expect it to hand hold me and walk me through all the steps.
For me that means, you don't care about your customers, all you want is a quick buck.
